apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sl-web-app
  template:
    metadata:
      labels:
        component: sl-web-app
    spec:
      containers:
        - name: frontend
          image: lcartwri/web-demo-app
          ports:
            - containerPort: 80