apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
images:
- name: lcartwri/web-demo-app
  newTag: c39bf76847522120c0bff0c4d601ef7ebb81311e
