apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: prod/
    repoURL: 'https://github.com/lcartwri/web-demo-deploy.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
