apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

resources:
  - frontend-test-service-lb.yml
  - frontend-test-deployment.yml
